### ISSUE TITLE
Exampl-app crash on start

### ISSUE THREAD

**Issue by samiujan** [remake/remake-cli#12]
**Describe the bug**

I installed node, npm and remake on a clean ubuntu 18 system

When I run

`npm run dev`,

it exits with error:
`
> remake-framework@1.1.0 dev /home/sami/code/example-app
> npm run asset-bundler-initial && concurrently --kill-others 'npm:nodemon' 'npm:asset-bundler-watch'

> remake-framework@1.1.0 asset-bundler-initial /home/sami/code/example-app
> node asset-bundler/initial-build.js
module.js:549
    throw err;
    ^
Error: Cannot find module 'upath'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sami/code/example-app/asset-bundler/process-file.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`
`
npm ERR! Linux 5.3.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "asset-bundler-initial"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! remake-framework@1.1.0 asset-bundler-initial: `node asset-bundler/initial-build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remake-framework@1.1.0 asset-bundler-initial script 'node asset-bundler/initial-build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remake-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node asset-bundler/initial-build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remake-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remake-framework
npm ERR! There is likely additional logging output above.
`
`
npm ERR! Please include the following file with any support request:
npm ERR!     /home/sami/code/example-app/npm-debug.log

npm ERR! Linux 5.3.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! remake-framework@1.1.0 dev: `npm run asset-bundler-initial && concurrently --kill-others 'npm:nodemon' 'npm:asset-bundler-watch'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remake-framework@1.1.0 dev script 'npm run asset-bundler-initial && concurrently --kill-others 'npm:nodemon' 'npm:asset-bundler-watch''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remake-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run asset-bundler-initial && concurrently --kill-others 'npm:nodemon' 'npm:asset-bundler-watch'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remake-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remake-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sami/code/example-app/npm-debug.log
`
`
**To Reproduce**
1. Install node
`sudo apt install -y nodejs`
2. Install npm
`sudo apt install -y npm`
3. Install remake
`npm install remake -g`
4. Generate example-app
`remake create example-app`
4. cd and run demo
`
cd example-app
npm run dev
`
**Expected behavior**
Application should start as per tutorial

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - NPM: 3.5.2
- node: v8.10.0

**Comment by panphora** [comment]
I'm looking into this now. Sorry for the really late response!

**Comment by panphora** [comment]
@samiujan You're right, this is an issue right now. I ran into a series of issues with trying to install remake on Ubuntu. 

Unfortunately, I don't have time to figure them out tonight, but I'll look into them again soon. I think the issue might be with the `remake` cmd line tool. Some of the packages it depends on might not be 100% compatible with Ubuntu. 

Sorry about this. I'll get back to you soon.

**Comment by panphora** [comment]
@samiujan We removed the bundler from Remake, so this shouldn't be an issue any more. Can you try again? We want to give you 2 free months of the Remake hosting plan for taking so long to respond to this issue. Send an email to david@remaketheweb.com if you'd like to take us up on this offer.
