### ISSUE TITLE
Project creation fails

### ISSUE THREAD

**Issue by vorkronor** [remake/remake-cli#25]
Tried to go through the tutorial, but I found a bug at "npx remake create". I got node v14.15.3, npm v 6.14.9, on a Big Sur M1 MacBook Pro. And this is what I got in my terminal.

`npx: installed 156 in 10.729s
✔ Creating new project.
✔ Tidy up new project directory.
(node:9120) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'notesaav/package.json'
    at Object.lstatSync (fs.js:1077:3)
    at replacizeFileSync (/Users/petr/.npm/_npx/9120/lib/node_modules/remake/node_modules/replace/replace.js:140:22)
    at module.exports (/Users/petr/.npm/_npx/9120/lib/node_modules/remake/node_modules/replace/replace.js:80:17)
    at cleanPackageJson (/Users/petr/.npm/_npx/9120/lib/node_modules/remake/utils/commands.js:320:3)
    at create (/Users/petr/.npm/_npx/9120/lib/node_modules/remake/utils/commands.js:48:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

When trying it out on my MacMini (2018 Core i5) still running on Catalina, Node v14.15.3, git from XCode (same as my M1 MBP). The results are the same (nothing is created), errors similar:

`npx: installed 156 in 10.231s
✔ Creating new project.
✔ Tidy up new project directory.
(node:5296) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'Notesaav/package.json'
    at Object.lstatSync (fs.js:1077:3)
    at replacizeFileSync (/Users/petr/.npm/_npx/5296/lib/node_modules/remake/node_modules/replace/replace.js:140:22)
    at module.exports (/Users/petr/.npm/_npx/5296/lib/node_modules/remake/node_modules/replace/replace.js:80:17)
    at cleanPackageJson (/Users/petr/.npm/_npx/5296/lib/node_modules/remake/utils/commands.js:320:3)
    at create (/Users/petr/.npm/_npx/5296/lib/node_modules/remake/utils/commands.js:48:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**To Reproduce**
Not sure how to reproduce since I did not back up my system before installing this and did not "try again". All I did was:

1. Downloaded and installed Node as directed by the tutorial
2. Install XCode (to get Git)
3. Open the standard Mac OS Terminal app
4. Create a "dev" directory in my ~ and cd into it
5. Run "npx remake create Notesaav" (tried with different app names just to be sure, e.g. "my-app")
6. Observe error ...

**Desktop (please complete the following information):**
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69

**Comment by panphora** [comment]
Hi @vorkronor, can you try again? And also make sure you don't have `remake` globally installed first?

Do you get the same result now?

**Comment by vorkronor** [comment]
Just letting you know that I got to try it again and create succeeded!
