### ISSUE TITLE
No Styling Applied To Default Starter Template

### ISSUE THREAD

**Issue by saideepesh000** [remake/remake-cli#28]
**Describe the bug**
There are no stylings in the default starter pack.

**To Reproduce**
1. npx remake create my-app
2. cd my-app
3. npm run dev and open http://localhost:3000
4. Styles are not applied

**Expected behavior**
It would be good if there are any styles applied to the app

**Screenshots**
![Screenshot (312)](https://user-images.githubusercontent.com/43727167/104904892-b372fc80-59a7-11eb-86a3-969fcb6d771e.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Firefox
 - Version: Latest

**Comment by panphora** [comment]
Thank you for the bug report @saideepesh000! I'm going to move this to the https://github.com/remake/remake-framework/ repository, since that's where the main framework lives. Only issues related to the CLI (command line interface) should go in this repo.

**Comment by panphora** [comment]
Here's the issue in the framework repo: https://github.com/remake/remake-framework/issues/35
